<!DOCTYPE html>
<html>
  <head>

    <script>
    function get(url) {
      // Return a new promise.
      return new Promise(function(resolve, reject) {
        var req = new XMLHttpRequest();
        req.open('GET', url);
        req.onload = function() {
          if (req.status == 200) {
            // Resolve the promise with the response text
            resolve(req.response);
          }
          else {
            reject(Error(req.statusText));
          }
        };

        req.onerror = function() {
          reject(Error("Network Error"));
        };

        // Make the request
        req.send();
      });
    }

    function getValue() {
      var promise = get('/value');
      
      promise.then(function(response) {
        return 3 * +response;
      })
      .then(function(data) {
        //try throwing an error here to see what happens
        // throw 'An error occurred';
        var result = 4 * Number(data);
        console.log('Function was passed ' + data + ' and will log ' + result);
        return result;
      })
      .then(function(data){
        console.log('Function will call server and return a promise');
        // here we make a second server call and chain a then to use the value returned
        return get('/value').then(function(val) { 
          var result = data * val;
          console.log('Server returned ' + val + ' so Function will return '  + result);
          return result;
        });
      })
      .then(function(data){
        var result = 3 * Number(data);
        console.log('Function was passed ' + data + ' and will return ' + result);
        return result;
      })
      .catch(function(error) {
        console.log(error);
        alert('There was an error: ' + error);
      });

      //This starts a new chain
      promise.then(function(data){
        console.log('data', data);
      });

    }

    </script>
  </head>
  <body>
    <button onclick="getValue()">click me and watch the console</button>
  </body>
</html>